package com.ayat.irisresearch;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.view.Gravity;
import android.content.Intent;
import android.widget.*;
import java.time.LocalDateTime;
import java.util.*;

public class ChartActivity extends Activity {
    private TextView text(String value,float size){TextView t=new TextView(this);t.setText(value);t.setTextColor(Color.WHITE);t.setTextSize(size);t.setPadding(10,12,10,12);t.setTextDirection(TextView.TEXT_DIRECTION_RTL);return t;}
    private String planetMeaning(int i){String[] m={"خورشید: هویت، اراده، هدف و شیوه ابراز خود.","ماه: نیازهای عاطفی، امنیت، عادت‌ها و واکنش‌های ناخودآگاه.","عطارد: فکر کردن، یادگیری، ارتباط، مذاکره و تصمیم‌گیری.","زهره: عشق، جذب شدن، سلیقه، ارزش‌ها و شیوه رابطه.","مریخ: انرژی، انگیزه، رقابت، خشم و نحوه اقدام.","مشتری: رشد، باورها، آموزش، فرصت و گسترش.","زحل: مسئولیت، محدودیت، نظم، تعهد و درس‌های بلندمدت.","اورانوس: تغییر، استقلال، نوآوری و شکستن الگوهای قدیمی.","نپتون: تخیل، معنویت، ایده‌آل‌گرایی و مرزهای مبهم.","پلوتو: دگرگونی، قدرت، بحران و بازسازی عمیق."};return m[i];}
    private String aspectGuide(String a){if(a.contains("هم‌نشینی"))return a+" — دو انرژی در یک موضوع پررنگ‌تر می‌شوند.";if(a.contains("تسدیس"))return a+" — در سنت معمولاً فرصت همکاری تعبیر می‌شود.";if(a.contains("تربیع"))return a+" — معمولاً تنش یا چالشی برای مدیریت است.";if(a.contains("تثلیث"))return a+" — معمولاً جریان روان‌تر و استعداد تعبیر می‌شود.";if(a.contains("مقابله"))return a+" — معمولاً کشمکش دو قطب و نیاز به تعادل است.";return a;}
    private String quickAnalysis(List<Double> p){int sun=AstrologyEngine.sign(p.get(0)),moon=AstrologyEngine.sign(p.get(1));StringBuilder s=new StringBuilder();s.append("تحلیل اولیه چارت\n\n");s.append("☉ خورشید در ").append(AstrologyEngine.signName(p.get(0))).append(" — در تفسیر سنتی، هویت، هدف و سبک ابراز خود.\n\n");s.append("☽ ماه در ").append(AstrologyEngine.signName(p.get(1))).append(" — نیازهای احساسی، امنیت و واکنش عاطفی.\n\n");s.append("ترکیب خورشید و ماه: ");if(sun==moon)s.append("تأکید نمادین روی یک نشانه و هم‌راستایی بیشتر بین هویت و نیاز عاطفی.");else s.append("دو لایه متفاوت‌اند؛ برای تحلیل باید عنصر، کیفیت، زهره، مریخ، خانه‌ها و جنبه‌ها کنار هم دیده شوند.");s.append("\n\n");s.append("عشق و ازدواج: زهره، مریخ، ماه، خانه هفتم و حاکم آن باید کنار هم بررسی شوند.\n\n");s.append("شغل: خورشید، عطارد، مریخ، مشتری و خانه‌های 2/6/10 بررسی می‌شوند.\n\n");s.append("تغذیه: گزارش جامع یک راهنمای نمادین غذایی بر اساس عنصر نشانه می‌دهد؛ نسخه پزشکی یا رژیم درمانی نیست.\n\n");s.append("پول و سرمایه‌گذاری: فقط چارچوب نمادین؛ تصمیم واقعی باید بر هدف، افق زمانی، ریسک، نقدشوندگی و تنوع‌بخشی تکیه کند.\n\n");s.append("سلامت: نمادشناسی زودیاک ابزار تشخیص بیماری نیست.");return s.toString();}

    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(18,18,18,18);box.setBackgroundColor(Color.rgb(11,16,32));TextView title=new TextView(this);title.setText("نمودار تولد و موتورهای تحلیل");title.setTextColor(Color.WHITE);title.setTextSize(22);title.setGravity(Gravity.CENTER);box.addView(title);box.addView(text("راهنما: نقاط داخل نمودار داده خام هستند. برای تفسیر شخصیت، عشق، کار، تغذیه، خانواده، تحصیل، سفر و دوره‌های زمانی، «تحلیل اولیه» و سپس «گزارش جامع» را بخوانید.",15));ChartView chart=new ChartView(this);box.addView(chart,new LinearLayout.LayoutParams(-1,650));String date=getIntent().getStringExtra("date");String rawTime=getIntent().getStringExtra("time");String normalizedTime=rawTime;if(normalizedTime!=null&&normalizedTime.length()==5)normalizedTime+=":00";final String time=normalizedTime;try{LocalDateTime dt=LocalDateTime.parse(date+"T"+time);List<Double> p=AstrologyEngine.approximateLongitudes(dt);chart.setLongitudes(p);TextView analysis=text(quickAnalysis(p),16);analysis.setBackgroundColor(Color.rgb(22,30,52));box.addView(analysis);Button research=new Button(this);research.setText("باز کردن گزارش جامع و تحلیل جزئی");research.setTextSize(16);research.setOnClickListener(v->openResearch(date,time));box.addView(research,new LinearLayout.LayoutParams(-1,-2));Button couple=new Button(this);couple.setText("تحلیل زوجین / مقایسه دو چارت");couple.setTextSize(16);couple.setOnClickListener(v->startActivity(new Intent(this,CoupleAnalysisActivity.class)));box.addView(couple,new LinearLayout.LayoutParams(-1,-2));StringBuilder s=new StringBuilder();s.append("موقعیت اجرام — داده خام برای بررسی پژوهشی\n\n");for(int i=0;i<p.size();i++)s.append(AstrologyEngine.PLANETS[i]).append(": ").append(String.format(Locale.US,"%.2f",p.get(i))).append("° — ").append(AstrologyEngine.signName(p.get(i))).append("\n").append(planetMeaning(i)).append("\n\n");s.append("جنبه‌ها و راهنمای تفسیر:\n");List<String> aspects=AstrologyEngine.aspects(p);if(aspects.isEmpty())s.append("جنبه اصلی در محدوده فعلی محاسبه نشد.\n");for(String a:aspects)s.append("• ").append(aspectGuide(a)).append("\n");double moonSid=VedicEngine.sidereal(p.get(1));s.append("\nودیک — راشی ماه: ").append(VedicEngine.rashi(moonSid)).append("\nناکشترا: ").append(VedicEngine.nakshatra(moonSid));box.addView(text(s.toString(),15));}catch(Exception e){box.addView(text("خطا در محاسبه چارت: "+e.getMessage(),16));}ScrollView sv=new ScrollView(this);sv.addView(box);setContentView(sv);}
    private void openResearch(String date,String time){Intent i=new Intent(this,AnalysisSummaryActivity.class);i.putExtra("name",getIntent().getStringExtra("name"));i.putExtra("date",date);i.putExtra("time",time);i.putExtra("city",getIntent().getStringExtra("city"));i.putExtra("latitude",getIntent().getDoubleExtra("latitude",0));i.putExtra("longitude",getIntent().getDoubleExtra("longitude",0));i.putExtra("timezone",getIntent().getStringExtra("timezone"));startActivity(i);}
}
